### PR TITLE
placeholder

### PR DESCRIPTION
**Pull request by ameliapractice**

### CODE REVIEW

**Comment by TowCenterCUJ** [comment]
Hi Amelia,

Hope you are well - please let me know if we'll see you this Friday at the
Fellows' lunch - it would be great to catch up.

With best regards,

Liz

On Fri, Aug 7, 2015 at 1:26 AM, Amelia Marzec notifications@github.com
wrote:

> Merged #2 https://github.com/TowCenter/YouAreHere/pull/2.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TowCenter/YouAreHere/pull/2#event-376015543.

## 

Elizabeth Boylan
Administrator
Tow Center for Digital Journalism
Columbia University Graduate School of Journalism
2950 Broadway - Pulitzer Hall
New York, NY 10027

212.854.1951

**Comment by ameliapractice** [comment]
Hey Liz,
I'm in Canada but will be back Thursday! Spotty access to email!
Let me know what the info is for the Friday lunch. Friday is kind of
flexible!
Thanks!
-Amelia

**Comment by TowCenterCUJ** [comment]
Hi Amelia,

This Friday, August 21st at noon, we'll be having the first of our Tow
Fellows lunches.

Please bring a brown-bag lunch to the Brown Institute space - - we'll plan
on spending an hour catching up on the progress of the last month, and
looking ahead.

We hope you will be able to join us.  Please let me know if you have any
questions.

With best regards,

Liz

On Tue, Aug 18, 2015 at 4:03 PM, Amelia Marzec notifications@github.com
wrote:

> Hey Liz,
> I'm in Canada but will be back Thursday! Spotty access to email!
> Let me know what the info is for the Friday lunch. Friday is kind of
> flexible!
> Thanks!
> -Amelia
> 
> On Tue, Aug 18, 2015 at 9:22 AM, TowCenterCUJ notifications@github.com
> wrote:
> 
> > Hi Amelia,
> > 
> > Hope you are well - please let me know if we'll see you this Friday at
> > the
> > Fellows' lunch - it would be great to catch up.
> > 
> > With best regards,
> > 
> > Liz
> > 
> > On Fri, Aug 7, 2015 at 1:26 AM, Amelia Marzec notifications@github.com
> > wrote:
> > 
> > > Merged #2 https://github.com/TowCenter/YouAreHere/pull/2.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/TowCenter/YouAreHere/pull/2#event-376015543.
> > 
> > ## 
> > 
> > Elizabeth Boylan
> > Administrator
> > Tow Center for Digital Journalism
> > Columbia University Graduate School of Journalism
> > 2950 Broadway - Pulitzer Hall
> > New York, NY 10027
> > 
> > 212.854.1951
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/TowCenter/YouAreHere/pull/2#issuecomment-132265379.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TowCenter/YouAreHere/pull/2#issuecomment-132333903.

## 

Elizabeth Boylan
Administrator
Tow Center for Digital Journalism
Columbia University Graduate School of Journalism
2950 Broadway - Pulitzer Hall
New York, NY 10027

212.854.1951

**Comment by ameliapractice** [comment]
Ok great! I will be there. Is that the same place we had the orientation?
-Amelia

**Comment by TowCenterCUJ** [comment]
Yep!  See you on Friday - and remind your teammates!

On Tue, Aug 18, 2015 at 7:08 PM, Amelia Marzec notifications@github.com
wrote:

> Ok great! I will be there. Is that the same place we had the orientation?
> -Amelia
> On Aug 18, 2015 1:16 PM, "TowCenterCUJ" notifications@github.com wrote:
> 
> > Hi Amelia,
> > 
> > This Friday, August 21st at noon, we'll be having the first of our Tow
> > Fellows lunches.
> > 
> > Please bring a brown-bag lunch to the Brown Institute space - - we'll
> > plan
> > on spending an hour catching up on the progress of the last month, and
> > looking ahead.
> > 
> > We hope you will be able to join us. Please let me know if you have any
> > questions.
> > 
> > With best regards,
> > 
> > Liz
> > 
> > On Tue, Aug 18, 2015 at 4:03 PM, Amelia Marzec <notifications@github.com
> > 
> > wrote:
> > 
> > > Hey Liz,
> > > I'm in Canada but will be back Thursday! Spotty access to email!
> > > Let me know what the info is for the Friday lunch. Friday is kind of
> > > flexible!
> > > Thanks!
> > > -Amelia
> > > 
> > > On Tue, Aug 18, 2015 at 9:22 AM, TowCenterCUJ <
> > > notifications@github.com>
> > > wrote:
> > > 
> > > > Hi Amelia,
> > > > 
> > > > Hope you are well - please let me know if we'll see you this Friday
> > > > at
> > > > the
> > > > Fellows' lunch - it would be great to catch up.
> > > > 
> > > > With best regards,
> > > > 
> > > > Liz
> > > > 
> > > > On Fri, Aug 7, 2015 at 1:26 AM, Amelia Marzec <
> > > > notifications@github.com>
> > > > wrote:
> > > > 
> > > > > Merged #2 https://github.com/TowCenter/YouAreHere/pull/2.
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > https://github.com/TowCenter/YouAreHere/pull/2#event-376015543.
> > > > 
> > > > ## 
> > > > 
> > > > Elizabeth Boylan
> > > > Administrator
> > > > Tow Center for Digital Journalism
> > > > Columbia University Graduate School of Journalism
> > > > 2950 Broadway - Pulitzer Hall
> > > > New York, NY 10027
> > > > 
> > > > 212.854.1951
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > > > https://github.com/TowCenter/YouAreHere/pull/2#issuecomment-132265379
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/TowCenter/YouAreHere/pull/2#issuecomment-132333903
> > > .
> > 
> > ## 
> > 
> > Elizabeth Boylan
> > Administrator
> > Tow Center for Digital Journalism
> > Columbia University Graduate School of Journalism
> > 2950 Broadway - Pulitzer Hall
> > New York, NY 10027
> > 
> > 212.854.1951
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/TowCenter/YouAreHere/pull/2#issuecomment-132337810.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TowCenter/YouAreHere/pull/2#issuecomment-132387336.

## 

Elizabeth Boylan
Administrator
Tow Center for Digital Journalism
Columbia University Graduate School of Journalism
2950 Broadway - Pulitzer Hall
New York, NY 10027

212.854.1951

**Pull request merged**
